name: atmos-pro-example-basic

license: APACHE2

github_repo: cloudposse-examples/atmos-pro-example-basic

description: |-
  A basic example demonstrating how to use Atmos Pro with GitHub Actions for infrastructure deployment. This repository shows the minimal configuration needed to get started with Atmos Pro workflows.

introduction: |-
  This is a basic example repository that demonstrates how to use Atmos Pro with GitHub Actions for infrastructure deployment. It provides a minimal setup to help you understand the core concepts of Atmos Pro workflows.

  For comprehensive documentation and advanced features, visit [atmos-pro.com/docs](https://atmos-pro.com/docs).

usage: |-

  This example demonstrates the minimal configuration needed to use Atmos Pro with GitHub Actions. The workflow is simple:

  ### 1. Create a Pull Request
  When you create a pull request, it automatically triggers the **plan** workflow. This will:
  - Run `atmos plan` for all affected components
  - Show you what changes will be made to your infrastructure
  - Provide feedback in the PR comments

  ### 2. Merge the Pull Request
  When you merge the pull request, it automatically triggers the **apply** workflow. This will:
  - Run `atmos apply` for all affected components
  - Apply the planned changes to your infrastructure
  - Update the deployment status

  ## Configuration

  The minimal configuration includes:
  - `atmos.yaml` - Main Atmos configuration file
  - `.github/workflows/` - GitHub Actions workflows for plan and apply
  - `components/` - Your infrastructure components
  - `stacks/` - Stack configurations

  ## Getting Started

  1. Fork this repository
  2. Configure your AWS credentials in GitHub Secrets
  3. Update the stack configurations in `stacks/` to match your environment
  4. Create a pull request to test the plan workflow
  5. Merge the PR to trigger the apply workflow

  For more detailed configuration options and advanced features, refer to the [Atmos Pro documentation](https://atmos-pro.com/docs).

contributors: []
