# yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

# Define common values for all components in this stack.
vars:
  stage: nonprod

# Import other Atmos stack configurations and deep merge them into this stack.
import:
  - ./_defaults

# Define components to deploy in this Atmos stack.
components:
  terraform:
    # This is a deployment of the "my-example-component-1" component
    my-example-component-1:
      vars:
        foo: "nonprod foo d"
        bar: "nonprod bar a"

    # This is an example of a component that depends on another component in this stack.
    my-example-component-2:
      settings:
        depends_on:
          1: 
            component: my-example-component-1
      vars:
        foo: "nonprod foo c"
        bar: "nonprod bar d"
