name: 👽 Atmos Pro Terraform Apply
run-name: apply ${{ inputs.component }}/${{ inputs.stack }}/${{ inputs.atmos_pro_run_id}}

on:
  workflow_dispatch:
    inputs:
      atmos_pro_run_id:
        description: "Atmos Pro Run ID"
        type: string
      sha:
        description: "Commit SHA"
        type: string
      component:
        description: "Component"
        required: true
        type: string
      stack:
        description: "Stack"
        required: true
        type: string
      github_environment:
        description: "GitHub Environment"
        required: true
        type: string

# Avoid running the same stack in parallel mode (from different workflows)
# This applied to across workflows to both plan and apply
concurrency:
  group: "${{ inputs.stack }}-${{ inputs.component }}"
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  statuses: write # This is required to post status checks back to the PR commit  

jobs: 
  atmos-apply:
    name: ${{ inputs.component }}-${{ inputs.stack }}

    # The GitHub environment is defined in Atmos Pro settings.
    # Typically this is <tenant>-<stage>
    environment: ${{ inputs.github_environment }}

    runs-on:
      - "ubuntu-latest"

    steps:
      - uses: unfor19/install-aws-cli-action@v1

      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v3
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha }}

      - name: Install Toolchain
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          atmos toolchain install
          atmos toolchain env --format github

      - name:  Apply Atmos Component
        shell: bash
        env:
          # Workspace ID is required for uploading the plan status to Atmos Pro.
          ATMOS_PRO_WORKSPACE_ID: ${{ vars.ATMOS_PRO_WORKSPACE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATMOS_PROFILE: github
          GITHUB_SHA: ${{ inputs.sha }}
        run: |
          atmos terraform deploy ${{ inputs.component }} -s ${{ inputs.stack }} --upload-status
